webtalk_init -webtalk_dir C:/ProySisEmb/Proy_Vivado/AddRoundKey_Decryption/AddRoundKey_Decryption.sim/sim_1/synth/func/xsim/xsim.dir/AddRoundKey_Decrypt_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May  1 12:44:48 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5ff7e70a-06c1-44eb-8888-605cd371ec96" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1d8000445b5848d9909e5cb124b6d822" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "12852_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2259198936 -regid "" -xml C:/ProySisEmb/Proy_Vivado/AddRoundKey_Decryption/AddRoundKey_Decryption.sim/sim_1/synth/func/xsim/xsim.dir/AddRoundKey_Decrypt_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/ProySisEmb/Proy_Vivado/AddRoundKey_Decryption/AddRoundKey_Decryption.sim/sim_1/synth/func/xsim/xsim.dir/AddRoundKey_Decrypt_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/ProySisEmb/Proy_Vivado/AddRoundKey_Decryption/AddRoundKey_Decryption.sim/sim_1/synth/func/xsim/xsim.dir/AddRoundKey_Decrypt_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
